/**
 * Standardized Enterprise Error Codes
 */
module.exports = {
  ERR_UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  ERR_FORBIDDEN: 'ERR_FORBIDDEN',
  ERR_NOT_FOUND: 'ERR_NOT_FOUND',
  ERR_VALIDATION: 'ERR_VALIDATION',
  ERR_DUPLICATE_ITEM: 'ERR_DUPLICATE_ITEM',
  ERR_STORAGE_LIMIT: 'ERR_STORAGE_LIMIT',
  ERR_TELEGRAM_API: 'ERR_TELEGRAM_API',
  ERR_INTERNAL_SERVER: 'ERR_INTERNAL_SERVER'
};
