/**
 * Enterprise Roles & Permissions
 */
const ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN'
};

const PERMISSIONS = {
  MANAGE_OWN_FILES: 'MANAGE_OWN_FILES',
  MANAGE_OWN_FOLDERS: 'MANAGE_OWN_FOLDERS',
  CREATE_SHARE_LINKS: 'CREATE_SHARE_LINKS',
  ADMIN_VIEW_DASHBOARD: 'ADMIN_VIEW_DASHBOARD',
  ADMIN_MANAGE_USERS: 'ADMIN_MANAGE_USERS',
  ADMIN_BAN_USERS: 'ADMIN_BAN_USERS',
  ADMIN_VIEW_LOGS: 'ADMIN_VIEW_LOGS',
  SUPER_ADMIN_ALL: 'SUPER_ADMIN_ALL'
};

module.exports = {
  ROLES,
  PERMISSIONS
};
